name: rate-cron
on:
  schedule:
    - cron: '30 0,12 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route to calculate rate
        run: |
          curl --request POST \
          --url 'https://roger-bot.space/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.CRON_API_KEY }}'
