name: mood-cron
on:
  schedule:
    - cron: "0 0 * * MON-FRI"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route to ask for MOOD
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://rogerbot.tech/api/ask-mood-cron
          configuration: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.CRON_API_KEY }}"} }'
          retry: true
