name: rate-cron
on:
  schedule:
    - cron: "0 23,11 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route to calculate rate
        run: |
          curl --request POST \
          --url 'https://rogerbot.tech/api/rate-cron' \
          --header 'Authorization: Bearer ${{ secrets.CRON_API_KEY }}'
