name: stata-cron
on:
  schedule:
    - cron: "0 23 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route to recalculate user rate statistics
        run: |
          curl --request POST \
          --url 'https://rogerbot.tech/api/stata-cron' \
          --header 'Authorization: Bearer ${{ secrets.CRON_API_KEY }}'
